### ISSUE TITLE
Angular unit testing by mocking ApplicationInsights with AI connection string.

### ISSUE THREAD

**Issue by ranjithh18** [microsoft/applicationinsights-angularplugin-js#77]
I need to write an angular unit testing by mocking an Application Insight object without using a connection string. Please find the code. when I write TC with a dummy string it throws an error on getTraceID (`this.appInsights.context.telemetryTrace.traceID`) that _Please provide instrumentation key_. 

```
import { Injectable } from '@angular/core';
import { ApplicationInsights, DistributedTracingModes } from '@microsoft/applicationinsights-web';
import { environment } from '../../../environments/environment';
import { AngularPlugin } from '@microsoft/applicationinsights-angularplugin-js';
import { Router } from '@angular/router';

@Injectable({
    providedIn: 'root'
})
export class MonitoringService {
    private appInsights: ApplicationInsights;

    constructor(private router: Router) {
        this.setupApplicationInsights();
    }

    setupApplicationInsights() {
        if (environment.applicationInsights.connectionString) {
            const angularPlugin = new AngularPlugin();
            this.appInsights = new ApplicationInsights({
                config: {
                    connectionString: environment.applicationInsights.connectionString,
                    autoTrackPageVisitTime: true,
                    distributedTracingMode: DistributedTracingModes.W3C,
                    isBeaconApiDisabled: false,
                    enableCorsCorrelation: true,
                    enableAutoRouteTracking: true,
                    enableAjaxPerfTracking: true,
                    enableAjaxErrorStatusText: true,
                    enableRequestHeaderTracking: true,
                    enableResponseHeaderTracking: true,
                    enableUnhandledPromiseRejectionTracking: true,
                    disableCookiesUsage: true,
                    extensions: [angularPlugin],
                    extensionConfig: {
                        [angularPlugin.identifier]: {
                            router: this.router
                        }
                    }
                }
            });

            this.appInsights.loadAppInsights();

            const telemetryInitializer = (envelope) => {
                envelope.tags['ai.cloud.role'] = environment.applicationInsights.role;
            };
            this.appInsights.addTelemetryInitializer(telemetryInitializer);
        }
    }

    getTraceID(): string {
        return this.appInsights.context.telemetryTrace.traceID;
    }
}

```

```
import { TestBed } from '@angular/core/testing';

import { MonitoringService } from './monitoring.service';
import any = jasmine.any;

describe('MonitoringService', () => {
    let service: MonitoringService;

    beforeEach(() => {
        TestBed.configureTestingModule({});
        service = TestBed.inject(MonitoringService);
    });

    it('should be created', () => {
        expect(service).toBeTruthy();
    });
    it ('should create app-insight and get traceID', () => {
        expect(service.getTraceID()).toEqual(any(String));
    });
});

```

Error Message

```
Error: Please provide instrumentation key
	    at throwError (node_modules/@microsoft/applicationinsights-web/node_modules/@microsoft/applicationinsights-core-js/dist-esm/JavaScriptSDK/HelperFuncs.js:529:11)
	    at AppInsightsCore.apply (node_modules/@microsoft/applicationinsights-web/node_modules/@microsoft/applicationinsights-core-js/dist-esm/JavaScriptSDK/BaseCore.js:51:31)
	    at Object.initialize (node_modules/@microsoft/dynamicproto-js/lib/dist/esm/dynamicproto-js.js:216:28)
	    at AppInsightsCore.apply [as initialize] (node_modules/@microsoft/applicationinsights-web/node_modules/@microsoft/applicationinsights-core-js/dist-esm/JavaScriptSDK/AppInsightsCore.js:24:23)
	    at AppInsightsCore.initialize (node_modules/@microsoft/dynamicproto-js/lib/dist/esm/dynamicproto-js.js:324:29)
	    at func (node_modules/@microsoft/applicationinsights-web/dist-esm/Initialization.js:324:24)
	    at doPerf (node_modules/@microsoft/applicationinsights-web/node_modules/@microsoft/applicationinsights-core-js/dist-esm/JavaScriptSDK/PerfManager.js:176:12)
	    at Initialization.loadAppInsights (node_modules/@microsoft/applicationinsights-web/dist-esm/Initialization.js:317:15)
	    at MonitoringService.setupApplicationInsights (src/app/share/services/monitoring.service.ts:43:30)
	    at new MonitoringService (src/app/share/services/monitoring.service.ts:14:14)
	TypeError: Cannot read properties of undefined (reading 'getTraceID')
	    at UserContext.apply (src/app/share/services/monitoring.service.spec.ts:18:24)
	    at _ZoneDelegate.invoke (node_modules/zone.js/fesm2015/zone.js:372:26)
	    at ProxyZoneSpec.onInvoke (node_modules/zone.js/fesm2015/zone-testing.js:287:39)
	    at _ZoneDelegate.invoke (node_modules/zone.js/fesm2015/zone.js:371:52)
	    at Zone.run (node_modules/zone.js/fesm2015/zone.js:134:43)
	    at runInTestZone (node_modules/zone.js/fesm2015/zone-testing.js:582:34)
	    at UserContext.<anonymous> (node_modules/zone.js/fesm2015/zone-testing.js:597:20)
	    at <Jasmine>

```

**Comment by MSNev** [comment]
The `Cannot read properties of undefined (reading 'getTraceID')` is a side effect of the SDK failing to initialize because no valid `instrumentationKey` was provided.

There are 2 options
- Provide a 'dummy' valid-ish "looking" instrumentation key as part of the `connectionString` or 
- directly as part of the config (For testing -- so you would need to "switch" your runtime config)

You could also add the `disableInstrumentationKeyValidation` config entry to "disable" the ikey validation, so then it doesn't have to be valid either and can just be something like "myTest-IKey"
